# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hipster coding blog
email: polkovnikov13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Блог, мотивирующий меня что-то делать
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dp9v.github.io" # the base hostname & protocol for your site
twitter_username: DemAn_13
github_username:  dp9v

# Build settings
markdown: kramdown
