# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hipster coding blog
tagline: Самоотивирующий блог
description: >
email: polkovnikov13@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dp9v.github.io" # the base hostname & protocol for your site


github:
  url:               #"https://dp9v.github.io"


author:
  name:              "Polkovnikov Dmitriy"
  email:             "Polkovnikov13@gmail.com"
  twitter:           "DemAn_13"
  github:            "dp9v"
  facebook:          "polkovnikov13"

navigation:
- title: О блоге
  url: /about
- title: Архив
  url: /writing
- title: Контакты
  url: /contact

paginate:            10
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
